apiVersion: v1
kind: Service
metadata:
  name: pbl-bluegreen-service
spec:
  type: NodePort
  selector:
    app: pbl-cicd
    version: green
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081